[package]
name = "arpy-client"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Client for the Arpy RPC library"
keywords = ["RPC", "web", "wasm"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
async-trait = "0.1.63"
bincode = "1.3.3"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
js-sys = "0.3.60"
futures = "0.3.25"
tokio = { version = "1.25.0", default-features = false, features = [
    "macros",
    "sync",
] }
pin-project = "1.0.12"
serde_json = "1.0.91"
slotmap = { version = "1.0.6", features = ["serde"] }
wasm-bindgen-futures = "0.4.34"
tokio-stream = "0.1.11"
