[package]
name = "arpy-client"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Client for the Arpy RPC library"
keywords = ["RPC", "web", "wasm"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "sync"] }
slotmap = { workspace = true, features = ["serde"] }
arpy = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
tokio-stream = { workspace = true }
