[package]
name = "arpy-macros"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Macros for the Arpy RPC library"
keywords = ["RPC", "web"]
categories = [
    "web-programming",
    "network-programming",
]

[lib]
proc-macro = true

[dependencies]
syn = "1.0.86"
quote = "1.0.15"
heck = "0.4.0"
