[package]
name = "arpy-axum"
version = "0.1.0"
edition = "2021"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
description = "Axum server for the Arpy RPC library"
keywords = ["RPC", "web", "axum", "http", "websocket"]
categories = [
    "web-programming",
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
arpy-server = { path = "../server" }
async-trait = "0.1.63"
axum = { version = "0.6.3", features = ["ws", "headers"] }
ciborium = "0.2.0"
hyper = "0.14.23"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.21.2", features = ["full"] }
anyhow = "1.0.68"
tracing = "0.1.37"
futures = "0.3.25"
serde_urlencoded = "0.7.1"
include-doc = "0.0.2"
