[package]
name = "arpy-axum"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Axum server for the Arpy RPC library"
keywords = ["RPC", "web", "axum", "http", "websocket"]
categories = [
    "web-programming",
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
arpy-server = { path = "../server", version = "0.1.0" }
async-trait = "0.1.63"
axum = { version = "0.6.3", features = ["ws", "headers"] }
ciborium = "0.2.0"
hyper = "0.14.23"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.21.2", features = ["full"] }
tracing = "0.1.37"
futures = "0.3.25"
serde_urlencoded = "0.7.1"
include-doc = "0.1.1"
