[package]
name = "arpy-axum"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Axum server for the Arpy RPC library"
keywords = ["RPC", "web", "axum", "http", "websocket"]
categories = [
    "web-programming",
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
axum = { workspace = true, features = ["ws", "headers"] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
arpy = { workspace = true }
arpy-server = { workspace = true }
async-trait = { workspace = true }
ciborium = { workspace = true }
hyper = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
serde_urlencoded = { workspace = true }
include-doc = { workspace = true }
