[package]
name = "arpy-actix"
version = "0.1.0"
edition = "2021"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
homepage = "https://github.com/simon-bourne/arpy"
repository = "https://github.com/simon-bourne/arpy"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
description = "Actix server for the Arpy RPC library"
keywords = ["RPC", "web", "actix", "http", "websocket"]
categories = [
    "web-programming",
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.0"
actix-ws = "0.2.5"
anyhow = "1.0.68"
arpy = { path = "../arpy", version = "0.1.0" }
arpy-server = { path = "../server", version = "0.1.0" }
ciborium = "0.2.0"
futures = "0.3.25"
serde = "1.0.152"
serde_json = "1.0.91"
serde_urlencoded = "0.7.1"
include-doc = "0.0.2"

[dev-dependencies]
arpy-test = { path = "../test" }
arpy-reqwest = { path = "../reqwest", version = "0.1.0" }
tokio = { version = "1.21.2", features = ["full"] }
reqwest = "0.11.14"
