[package]
name = "arpy-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-rt = "2.8.0"
actix-web = "4.3.0"
actix-ws = "0.2.5"
anyhow = "1.0.68"
arpy = { path = "../arpy" }
arpy-server = { path = "../server" }
ciborium = "0.2.0"
futures = "0.3.25"
serde_json = "1.0.91"

[dev-dependencies]
arpy-test = { path = "../test" }
arpy-reqwest = { path = "../reqwest" }
tokio = { version = "1.21.2", features = ["full"] }
reqwest = "0.11.14"
