[package]
name = "arpy-actix"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Actix server for the Arpy RPC library"
keywords = ["RPC", "web", "actix", "http", "websocket"]
categories = [
    "web-programming",
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
actix-rt = { workspace = true }
actix-web = { workspace = true }
actix-ws = { workspace = true }
arpy = { workspace = true }
arpy-server = { workspace = true }
ciborium = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
include-doc = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
arpy-test = { workspace = true }
arpy-reqwest = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true }
