[package]
name = "arpy-reqwasm"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Reqwasm client for the Arpy RPC library"
keywords = ["RPC", "web", "wasm"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "sync"] }
web-sys = { workspace = true, features = ["MessageEvent"] }
arpy = { workspace = true }
arpy-client = { workspace = true }
async-trait = { workspace = true }
ciborium = { workspace = true }
reqwasm = { workspace = true }
thiserror = { workspace = true }
js-sys = { workspace = true }
futures = { workspace = true }
include-doc = { workspace = true }
gloo-net = { workspace = true }
pin-project = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen-futures = { workspace = true }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }
arpy-test = { workspace = true }
