[package]
name = "arpy-reqwasm"
version = "0.1.0"
edition = "2021"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
description = "Reqwasm client for the Arpy RPC library"
keywords = ["RPC", "web", "wasm"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
async-trait = "0.1.63"
ciborium = "0.2.0"
reqwasm = "0.5.0"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
js-sys = "0.3.60"
futures = "0.3.25"
tokio = { version = "1.25.0", default-features = false, features = [
    "macros",
    "sync",
] }
include-doc = "0.0.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
arpy-test = { path = "../test" }
