[package]
name = "rpc-test-data"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rpc = { path = "../rpc" }
async-trait = "0.1.63"
serde = { version = "1.0.152", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rpc-axum = { path = "../axum" }
axum = { version = "0.6.3", features = ["ws", "headers"] }
tokio = { version = "1.21.2", features = ["full"] }
hyper = "0.14.23"
tower-http = { version = "0.3.5", features = ["cors"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
