[package]
name = "arpy"
version = "0.1.0"
edition = "2021"

[dependencies]
arpy-macros = { path = "../macros", version = "0.1.0" }
async-trait = "0.1.63"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
