[package]
name = "arpy"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Define RPC signatures and use them with various clients/servers"
keywords = ["RPC", "web"]
categories = [
    "web-programming",
    "network-programming",
]

[dependencies]
arpy-macros = { path = "../macros", version = "0.1.0" }
async-trait = "0.1.63"
futures = "0.3.26"
pin-project = "1.0.12"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"
