[package]
name = "arpy"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Define RPC signatures and use them with various clients/servers"
keywords = ["RPC", "web"]
categories = ["web-programming", "network-programming"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
arpy-macros = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
thiserror = { workspace = true }
