[package]
name = "arpy-example-common"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
arpy = { path = "../../packages/arpy" }
futures = "0.3.26"
serde = { version = "1.0.152", features = ["derive"] }
tokio-stream = "0.1.11"
