[package]
name = "arpy-example-common"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
arpy = { path = "../../packages/arpy" }
async-trait = "0.1.63"
serde = { version = "1.0.152", features = ["derive"] }
