[package]
name = "arpy-example-common"
version = { workspace = true }
edition = { workspace = true }
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
arpy = { workspace = true }
futures = { workspace = true }
tokio-stream = { workspace = true }
