[package]
name = "arpy-reqwest"
version = "0.1.0"
edition = "2021"
authors = ["Simon Bourne <simonbourne@gmail.com>"]
homepage = "https://github.com/simon-bourne/arpy"
repository = "https://github.com/simon-bourne/arpy"
readme = "../../README.md"
license = "MIT OR Apache-2.0"
description = "Reqwest client for the Arpy RPC library"
keywords = ["RPC", "web"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
async-trait = "0.1.63"
ciborium = "0.2.0"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"

[dev-dependencies]
arpy-test = { path = "../test" }
tokio = { version = "1.24.2", features = ["macros", "process"] }
