[package]
name = "arpy-reqwest"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Reqwest client for the Arpy RPC library"
keywords = ["RPC", "web"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
async-trait = "0.1.63"
ciborium = "0.2.0"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"

[dev-dependencies]
arpy-test = { path = "../test" }
tokio = { version = "1.24.2", features = ["macros", "process"] }
