[package]
name = "arpy-reqwest"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Reqwest client for the Arpy RPC library"
keywords = ["RPC", "web"]
categories = [
    "web-programming",
    "web-programming::http-client",
    "network-programming",
]

[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
arpy = { workspace = true }
async-trait = { workspace = true }
ciborium = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
arpy-test = { workspace = true }
tokio = { version = "1.24.2", features = ["macros", "process"] }
