[package]
name = "rpc-reqwest"
version = "0.1.0"
edition = "2021"

[dependencies]
rpc = { path = "../rpc" }
async-trait = "0.1.63"
ciborium = "0.2.0"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
thiserror = "1.0.38"

[dev-dependencies]
rpc-test = { path = "../test" }
tokio = { version = "1.24.2", features = ["macros", "process"] }
