[package]
name = "rpc-axum"
version = "0.1.0"
edition = "2021"

[dependencies]
rpc = { path = "../rpc" }
async-trait = "0.1.63"
axum = { version = "0.6.3", features = ["ws", "headers"] }
ciborium = "0.2.0"
hyper = "0.14.23"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
thiserror = "1.0.38"
tokio = { version = "1.21.2", features = ["full"] }
