[package]
name = "arpy-server"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
description = "Actix server for the Arpy"
keywords = ["RPC", "web", "actix", "http", "websocket"]
categories = [
    "web-programming",
    "web-programming::http-server",
    "web-programming::websocket",
    "network-programming",
]

[dependencies]
arpy = { path = "../arpy", version = "0.1.0" }
bincode = "1.3.3"
futures = "0.3.25"
serde = "1.0.152"
slotmap = { version = "1.0.6", features = ["serde"] }
thiserror = "1.0.38"
tokio = { version = "1.25.0", features = ["sync", "rt"] }
tracing = "0.1.37"
