[package]
name = "rpc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.63"
axum = { version = "0.6.3", features = ["ws", "headers"] }
ciborium = "0.2.0"
hyper = "0.14.23"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.21.2", features = ["full"] }
