[package]
name = "arpy-example-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
arpy-actix = { path = "../../packages/actix" }
arpy-server = { path = "../../packages/server" }
arpy-example-common = { path = "../common" }
env_logger = "0.10.0"
