[package]
name = "arpy-example-actix"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
arpy-actix = { path = "../../packages/actix" }
arpy-test = { path = "../../packages/test" }
arpy-server = { path = "../../packages/server" }
