[package]
name = "include-doc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.86"
quote = "1.0.15"
proc-macro-error = "1.0.4"
ra_ap_syntax = "0.0.149"
itertools = "0.10.5"
