[package]
name = "rpc-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
rpc-test = { path = "../test" }
rpc = { path = "../rpc" }
rpc-axum = { path = "../axum" }
rpc-reqwest = { path = "../reqwest" }
axum = { version = "0.6.3", features = ["ws", "headers"] }
reqwest = "0.11.14"
tokio = { version = "1.21.2", features = ["full"] }
