name: tests
on: [push, pull_request]
jobs:
  stable:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        rust: [1.66.1]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: clippy
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        target: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      if: ${{ !env.ACT }}
    - uses: actions-rs/install@v0.1
      with:
        crate: wasm-pack
        version: 0.10.2
    - run: cargo clippy --all-targets -- -D warnings -D clippy::all
    - run: cargo doc
    - run: cargo test --all-targets

  nightly:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly-2022-09-29]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        default: true
        components: rustfmt
    - uses: Swatinem/rust-cache@3bb3a9a087029c7bc392586cdc88cb6f66b9c6ef
      if: ${{ !env.ACT }}
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-udeps
    - run: cargo fmt --all -- --check
    - run: cargo udeps --all-targets
